language: en
pipeline:
- name: ConveRTTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: ConveRTFeaturizer
- name: DIETClassifier
  epochs: 75
  intent_classification: 'True'
  entity_recognition: 'True'
- name: EntitySynonymMapper
policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
- name: MappingPolicy
